version: '3.8'

services:
  cert-checker:
    build:
      context: ./cert_checker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db-service

  db-service:
    build:
      context: ./db_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/certmon
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=certmon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
