apiVersion: v1
kind: Secret
metadata:
  name: certmon-secrets
  namespace: certmon
type: Opaque
stringData:
  .env: |
    # Replace these values with your production values
    NODE_ENV=production
    FLASK_ENV=production
    LOG_LEVEL=info
    
    API_HOST=0.0.0.0
    API_PORT=5001
    API_URL=https://api.yourdomain.com
    SECRET_KEY=your_production_secret_key
    CORS_ORIGINS=https://certmon.yourdomain.com
    
    POSTGRES_HOST=certmon-db
    POSTGRES_PORT=5432
    POSTGRES_DB=certmon
    POSTGRES_USER=certmon
    POSTGRES_PASSWORD=your_production_db_password
    
    REDIS_HOST=certmon-redis
    REDIS_PORT=6379
    REDIS_DB=0
    
    SSL_VERIFY=true
    SSL_CERT_PATH=/etc/ssl/certs/ca-certificates.crt
