apiVersion: v1
kind: Secret
metadata:
  name: certmon-secrets
  namespace: certmon
type: Opaque
stringData:
  .env: |
    # Development environment configuration
    NODE_ENV=development
    FLASK_ENV=development
    LOG_LEVEL=debug
    
    API_HOST=0.0.0.0
    API_PORT=5001
    API_URL=http://localhost:5001
    SECRET_KEY=dev_secret_key_123
    CORS_ORIGINS=http://localhost:3000
    
    POSTGRES_HOST=certmon-db
    POSTGRES_PORT=5432
    POSTGRES_DB=certmon
    POSTGRES_USER=postgres
    POSTGRES_PASSWORD=postgres
    DATABASE_URL=postgresql://postgres:postgres@certmon-db:5432/certmon
    
    REDIS_HOST=certmon-redis
    REDIS_PORT=6379
    REDIS_DB=0
    REDIS_URL=redis://certmon-redis:6379/0
    
    # Celery configuration
    CELERY_BROKER_URL=redis://certmon-redis:6379/0
    CELERY_RESULT_BACKEND=redis://certmon-redis:6379/0
    
    # Development SSL settings
    SSL_VERIFY=false
    
    # Worker configuration
    WORKER_CONCURRENCY=4
    WORKER_MAX_TASKS_PER_CHILD=100
    WORKER_PREFETCH_MULTIPLIER=1
    
    # Frontend development settings
    REACT_APP_API_URL=http://localhost:5001
