apiVersion: v1
kind: ConfigMap
metadata:
  name: certmon-config
  namespace: certmon
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'certmon-api'
        static_configs:
          - targets: ['certmon-api:5000']
  
  nginx.conf: |
    server {
      listen 80;
      root /usr/share/nginx/html;
      location / {
        try_files $uri $uri/ /index.html;
      }
      location /api {
        proxy_pass http://certmon-api:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
