apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
  namespace: cert-mon
  labels:
    app: db-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
      - name: db-service
        image: localhost:5000/db-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: cert-mon-config
              key: API_HOST
        - name: API_PORT
          value: "8001"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: cert-mon-config
              key: LOG_LEVEL
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: cert-mon-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: cert-mon-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: cert-mon-config
              key: POSTGRES_DB
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: cert-mon-secrets
              key: JWT_SECRET
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: cert-mon-secrets
              key: JWT_ALGORITHM
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            secretKeyRef:
              name: cert-mon-secrets
              key: ACCESS_TOKEN_EXPIRE_MINUTES
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: cert-mon
spec:
  selector:
    app: db-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
